### ISSUE TITLE
TinyMCE CDN has been deprecated it seems

### ISSUE THREAD

**Issue by riker1** [bramley/phplist-plugin-tinymce#4] opened 2017-10-02 21:57 UTC
I had a problem today with our phplist 3.3.x instance. 

I found that TinyMCE is loaded from the CDN [version 4.6.7 (2017-09-18)](https://cdn.tinymce.com/4/tinymce.min.js) seems to have a nasty bug whereby trying to inserting an image or file doesn't work. All that happens is the browser spawns a new user window showing either the document or image. Inserting images or inline documents is completed unavailable.

I went to see if there was either a newer version or older version available to swap in. Apparently, it looks like the upstream provider of TinyMCE has moved their CDN to a ["Cloud" based distribution model](https://www.tinymce.com/download/) with an API-KEY needed to remove the warning from the editor within PHPList. Configuring PHPList to use the cloud CDN version as per their instructions //cloud.tinymce.com/stable/tinymce.min.js?apiKey=your_API_key (my key omitted) elFinder works perfectly. 

Registration seems to be free for an API-KEY but its an extra step needed to use. Also, the message doesn't go away that I registered but again elFinder works fine.

**Comment by bramley** [comment] 2017-10-03 08:04
I cannot repeat your problem but actually get another one that stops elfinder working.
Whereabouts is the warning displayed? Please can you add a small screenshot.

When I try to select an image within elfinder I get a javascript error
![image](https://user-images.githubusercontent.com/3147688/31115189-3e4f6698-a819-11e7-88f6-4f353d45d3a1.png)

I have looked at the elfinder issues but no-one seems to have reported this problem before. I will need to look at it further to decide what to do.

**Comment by bramley** [comment] 2017-10-04 03:48
The problem that I had yesterday seems to have been with tinymce and appears to have been fixed https://github.com/tinymce/tinymce/issues/3939. That may well have been the cause of your initial problem with trying to insert an image. Otherwise image inserting seems to work as before. 

There is a new, to me at least, "Powered by tinmymce" message, but that is not causing a problem and I haven't needed to register for an API key.
![image](https://user-images.githubusercontent.com/3147688/31159176-235b201a-a8bf-11e7-85b9-43743891dc91.png)

**Comment by bramley** [comment] 2017-10-05 15:56
@riker1 Do you have any further information about your problem, otherwise I will close this issue.

**Comment by riker1** [comment] 2017-10-05 16:02
I don't as soon as I used a different version of TinyMCE, the problem with elFinder (that you mentioned) went away... I guess close as "unreproducible" thanks for your time!  -Spencer

**Closed as completed** 2017-10-05 18:15 UTC
